---
- name: Configure macOS development environment
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  
  tasks:
    - name: Include homebrew role
      ansible.builtin.include_role:
        name: homebrew

    - name: Include dotfiles role
      ansible.builtin.include_role:
        name: dotfiles

    - name: Include macos-settings role
      ansible.builtin.include_role:
        name: macos-settings
