---

# Custom PRTG module
#- name: app | prtg | test
#  prtg:
#    api_user: gkeramidas
#    api_passhash: testing
#    prtg_url: https://prtg-prod:81

- name: app | Take the server out of the load balancer
  uri:
    url: http://localhost:8180/stop.txt
    method: POST
  when: 
    - ( 'app' in group_names )

- name: app | slack | Notify sysadmins on redis cache delay
  slack:
    msg: "_Patching on *{{ inventory_hostname }}* will resume when its cache expires_"
    token: "{{ slack_token }}"
    channel: "{{ slack_channel }}"
    username: "{{ slack_user }}"
    icon_emoji: "{{ slack_emoji }}"
  delegate_to: localhost
  when: 
    - ( 'app_prod' in group_names )
    - ( kernelup is defined )
    - ( 'linux-image' in kernelup.stdout )

- name: 'app_prod | Redis cache size {{ cache | default("unknown") }}'
  shell: redis-cli -h 127.0.1.1 -p 9849 info | grep 'db0:keys' || echo 'the cache is empty'
  register: cache
  until: cache.stdout.find("empty") != -1
  retries: 24
  delay: 300
  when: 
    - ( 'app_prod' in group_names )
    - ( 'linux-image' in kernelup.stdout )

# Added uninstalling java7 during patching, as it is a good idea to have the server reboot, to make sure there is no issue.
- name: app_prod | java | Remove java 7
  become: true
  apt:
    name: 
      - openjdk-7-jdk
      - openjdk-7-jre
      - openjdk-7-jre-headless
      - openjdk-7-jre-lib
      - openjdk-7-jre-zero
    state: absent
    autoclean: yes    # cleans the local repository of retrieved package files that can no longer be downloaded
    autoremove: yes   # remove unused dependency packages for all module states except build-dep
    force_apt_get: true
  register: rm_packages
  when: 
    - ( 'app_prod' in group_names )
    - ( 'linux-image' in kernelup.stdout )

- name: Print package uninstall output
  debug:
    msg: "{{ rm_packages.stdout_lines }}"
  when: 
    - rm_packages.changed

- name: app_prod | java | Create default java link (that tomcat8 config points to)
  become: true
  file:
    src: java-1.8.0-openjdk-amd64
    path: /usr/lib/jvm/default-java
    state: link
  when: 
    - rm_packages.changed

- name: app | slack | Notify sysadmins on Java 7 uninstall
  slack:
    msg: "_Removed Java 7 from *{{ inventory_hostname }}*_"
    token: "{{ slack_token }}"
    channel: "{{ slack_channel }}"
    username: "{{ slack_user }}"
    icon_emoji: "{{ slack_emoji }}"
  delegate_to: localhost
  when: 
    - rm_packages.changed