---

#- include_role:
#    name: common
#    tasks_from: account_setup_geomidas

- name: Set resolv.conf
  become: true
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root

- include_tasks: setup_lb.yml
  when: 
    - ( 'ha_k8s_rancher_lb' in group_names )

- include_tasks: setup_rancher_nodes.yml
  when:
    - ( 'ha_k8s_rancher' in group_names ) or
      ( 'ha_k8s_dev_masters' in group_names ) or
      ( 'ha_k8s_dev_workers' in group_names )
