---

- name: Disable SWAP since kubernetes can't work with swap enabled
  become: true
  shell: if [[ "$( swapon -s | wc -l )" -gt '2' ]] ; then swapoff -a ; echo changed ; else echo ok ; fi
  register: result
  changed_when: ( 'changed' in result.stdout )

- name: Disable SWAP in fstab
  become: true
  replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: result.changed

- name: Uninstall packages
  become: true
  apt:
    name:
      - mlocate
    state: absent

- name: Ensure dependencies are installed
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - cron
      - gnupg
      - software-properties-common
    state: present

- name: Add Docker apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add Docker repository
  become: true
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install Docker
  become: true
  package:
    name: docker-ce
    state: present
  notify: restart docker

- name: add registires
  become: true
  copy:
    src: docker_daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root

- name: create .docker directory
  become: true
  file:
    path: /root/.docker
    state: directory
  when: 
    - ( 'ha_k8s_dev_workers' in group_names )

- name: add docker credentials file
  become: true
  copy:
    src: docker_config.json
    dest: /root/.docker/config.json
    mode: 0644
    owner: root
    group: root
    backup: true
  when: 
    - ( 'ha_k8s_dev_workers' in group_names )
    
- name: Ensure Docker is started and enabled at boot
  become: true
  service:
    name: docker
    state: started
    enabled: true
