kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: moon 
  name: rmchromepods 
rules:
- apiGroups: [ "" ]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rmchromepods 
  namespace: moon
subjects:
- kind: ServiceAccount
  name: rmchromepods
  namespace: moon
roleRef:
  kind: Role
  name: rmchromepods
  apiGroup: "rbac.authorization.k8s.io"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rmchromepods
  namespace: moon

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rmchromepodsjob
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1 
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: rmchromepods
          containers:
          - name: rmchromepods
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - for pod in $(kubectl -n moon get pod | grep chrome | awk 'match($5,/[6-9]+m+*/) {print $1}') ; do kubectl delete pod $pod -n moon ; done
          restartPolicy: Never 
