---

- hosts:
    - app_java11
  vars:
    page_name: app - java11
    page_dir: "{{play_dir}}/app_java11"
  roles:
    - patching_status_pages

- hosts: 
    - app_dev
    - app_stag
  vars:
    page_name: app dev, app stag
    page_dir: "{{play_dir}}/dev"
  roles:
    - patching_status_pages

- hosts: 
    - app_prod
  vars:
    page_name: app prod
    page_dir: "{{play_dir}}/prod"
  roles:
    - patching_status_pages
  
- hosts: 
    - cache_prod
  vars:
    page_name: cache prod
    page_dir: "{{play_dir}}/cache_prod"
  roles:
    - patching_status_pages

- hosts: 
    - web_dev
    - web_stag
  vars:
    page_name: web dev, web stag
    page_dir: "{{play_dir}}/web_dev"
  roles:
    - patching_status_pages

- hosts: 
    - web_prod
  vars:
    page_name: web prod
    page_dir: "{{play_dir}}/web_prod"
  roles:
    - patching_status_pages

- hosts:
    - gt_dev
  vars:
    page_name: gt dev
    page_dir: "{{play_dir}}/gt_dev"
  roles:
    - patching_status_pages

- hosts:
    - gt_prod
  vars:
    page_name: gt prod
    page_dir: "{{play_dir}}/gt_prod"
  roles:
    - patching_status_pages

- hosts:
    - office
  vars:
    page_name: office
    page_dir: "{{play_dir}}/office"
  roles:
    - patching_status_pages

- hosts: localhost
  roles:
    - patching_status_server
